---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - kube.tools
  resources:
  - annot8rs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kube.tools
  resources:
  - annot8rs/finalizers
  verbs:
  - update
- apiGroups:
  - kube.tools
  resources:
  - annot8rs/status
  verbs:
  - get
  - patch
  - update
